"""
Django settings for theogony project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from .allowed_hosts import *
from .database import *
from .i18n import *
from .installed_apps import *
from .logging import *
from .middleware import *
from .password_validation import *
from .static import *
from .templates import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-nz#-i@u@^hp9$t(_a1gfm50^7n*i99y!%@uy&x)58pxutpk1+k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
