[tool.black]
extend-exclude = [".*/migrations/[0-9]{4}_.*.py"]

[tool.django-stubs]
django_settings_module = "tests.settings"

[tool.isort]
extend_skip_glob = ["**/migrations"]
known_django = "django,rest_framework"
line_length = 88
profile = "black"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"
skip_gitignore = true

[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
